@extends('admin.layout')

@section('admin-content')
    <div class="flex items-center justify-between"><div><h1 class="text-2xl font-bold">Resellers</h1><p class="mt-1 text-sm text-slate-600">Create and monitor white-label reseller accounts.</p></div></div>
    <div class="mt-6 grid gap-6 lg:grid-cols-[1fr_340px]">
        <div class="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-200 px-5 py-4"><h2 class="font-semibold">Reseller Accounts</h2></div><div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500"><tr><th class="px-5 py-3">Name</th><th class="px-5 py-3">Company</th><th class="px-5 py-3">Email</th><th class="px-5 py-3">Status</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($resellers as $reseller)<tr><td class="px-5 py-4 font-medium">{{ $reseller->name }}</td><td class="px-5 py-4">{{ $reseller->company_name }}</td><td class="px-5 py-4 text-slate-600">{{ $reseller->email }}</td><td class="px-5 py-4">{{ $reseller->status?->getLabel() ?? $reseller->status }}</td></tr>@empty<tr><td colspan="4" class="px-5 py-10 text-center text-slate-500">No resellers yet.</td></tr>@endforelse</tbody></table></div><div class="border-t border-slate-200 px-5 py-3">{{ $resellers->links() }}</div></div>
        <div class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-semibold">Create Reseller</h2><form method="POST" action="{{ route('admin.resellers.store') }}" class="mt-4 space-y-3">@csrf<input name="name" required placeholder="Full name" class="w-full rounded-lg border-slate-300 text-sm"><input name="email" type="email" required placeholder="Email" class="w-full rounded-lg border-slate-300 text-sm"><input name="company_name" placeholder="Company" class="w-full rounded-lg border-slate-300 text-sm"><input name="password" type="password" required minlength="8" placeholder="Temporary password" class="w-full rounded-lg border-slate-300 text-sm"><button class="w-full rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-blue-700">Create Reseller</button></form></div>
    </div>
@endsection
