[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:horizon]
process_name=%(program_name)s
command=php /var/www/artisan horizon
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/storage/logs/horizon.log
stopwaitsecs=3600

[program:rabbitmq-outbound-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/artisan rabbitmq:consume --queue=outbound-calls --consume-mode=poll
numprocs=1
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/storage/logs/rabbitmq-worker.log
stopwaitsecs=3600

[program:scheduler]
process_name=%(program_name)s
command=php /var/www/artisan schedule:work
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/storage/logs/scheduler.log
